"""convert datetime columns to timestamptz

Revision ID: 985ace416d98
Revises: 1621be72eeea
Create Date: 2025-11-12 04:09:07.863106

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '985ace416d98'
down_revision: str | Sequence[str] | None = '1621be72eeea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_graph_entity_attributes_jsonb'), table_name='graph_entity_attributes', postgresql_using='gin')
    op.drop_index(op.f('idx_graph_entity_embedding'), table_name='graph_entity_attributes', postgresql_ops={'name_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_graph_entity_group_id'), table_name='graph_entity_attributes')
    op.drop_index(op.f('idx_graph_entity_name_text'), table_name='graph_entity_attributes', postgresql_using='gin')
    op.drop_index(op.f('idx_graph_entity_type'), table_name='graph_entity_attributes')
    op.drop_table('graph_entity_attributes')
    op.alter_column('ambient_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('context_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('context_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('conversation_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('conversations_created_at_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_user_medium_ts_idx'), table_name='conversations', postgresql_where='((user_id IS NOT NULL) AND (medium IS NOT NULL))')
    op.drop_index(op.f('conversations_medium_timestamp_idx'), table_name='conversations', postgresql_where='(medium IS NOT NULL)')
    op.create_index('conversations_medium_timestamp_idx', 'conversations', ['medium', 'timestamp'], unique=False, postgresql_where=sa.text('medium IS NOT NULL'), postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('conversations_timestamp_idx'), table_name='conversations')
    op.create_index('conversations_timestamp_idx', 'conversations', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.alter_column('emotion_states', 'last_update',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('emotion_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('emotion_states_session_update_idx'), table_name='emotion_states')
    op.drop_index(op.f('emotion_states_last_update_idx'), table_name='emotion_states')
    op.create_index('emotion_states_last_update_idx', 'emotion_states', ['last_update'], unique=False, postgresql_ops={'last_update': 'DESC'})
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('entity_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('medium_presence', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('medium_presence', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('session_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('session_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('sessions_start_time_idx'), table_name='sessions')
    op.create_index('sessions_start_time_idx', 'sessions', ['start_time'], unique=False, postgresql_ops={'start_time': 'DESC'})
    op.alter_column('stimulus_history', 'timestamp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('stimulus_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('stimulus_history_timestamp_idx'), table_name='stimulus_history')
    op.create_index('stimulus_history_timestamp_idx', 'stimulus_history', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.alter_column('task_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('task_queue_created_idx'), table_name='task_queue')
    op.create_index('task_queue_created_idx', 'task_queue', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('task_queue_created_idx', table_name='task_queue', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('task_queue_created_idx'), 'task_queue', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('task_queue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('stimulus_history_timestamp_idx', table_name='stimulus_history', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('stimulus_history_timestamp_idx'), 'stimulus_history', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('stimulus_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('stimulus_history', 'timestamp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('sessions_start_time_idx', table_name='sessions', postgresql_ops={'start_time': 'DESC'})
    op.create_index(op.f('sessions_start_time_idx'), 'sessions', [sa.literal_column('start_time DESC')], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('session_summaries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('session_relationships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('medium_presence', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('medium_presence', 'last_heartbeat',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('entity_relationships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('entities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('emotion_states_last_update_idx', table_name='emotion_states', postgresql_ops={'last_update': 'DESC'})
    op.create_index(op.f('emotion_states_last_update_idx'), 'emotion_states', [sa.literal_column('last_update DESC')], unique=False)
    op.create_index(op.f('emotion_states_session_update_idx'), 'emotion_states', ['session_id', sa.literal_column('last_update DESC')], unique=False)
    op.alter_column('emotion_states', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('emotion_states', 'last_update',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('conversations_timestamp_idx', table_name='conversations', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('conversations_timestamp_idx'), 'conversations', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('conversations_medium_timestamp_idx', table_name='conversations', postgresql_where=sa.text('medium IS NOT NULL'), postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('conversations_medium_timestamp_idx'), 'conversations', ['medium', sa.literal_column('timestamp DESC')], unique=False, postgresql_where='(medium IS NOT NULL)')
    op.create_index(op.f('conversations_user_medium_ts_idx'), 'conversations', ['user_id', 'medium', sa.literal_column('timestamp DESC')], unique=False, postgresql_where='((user_id IS NOT NULL) AND (medium IS NOT NULL))')
    op.create_index(op.f('conversations_created_at_idx'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('conversation_segments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('context_cache', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('context_cache', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('ambient_notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('graph_entity_attributes',
    sa.Column('entity_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('name_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bot_thoughts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('importance_score', sa.TEXT(), server_default=sa.text("'low'::text"), autoincrement=False, nullable=True),
    sa.Column('last_discussed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("importance_score = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])", name=op.f('graph_entity_attributes_importance_score_check')),
    sa.PrimaryKeyConstraint('entity_uuid', name=op.f('graph_entity_attributes_pkey'))
    )
    op.create_index(op.f('idx_graph_entity_type'), 'graph_entity_attributes', ['entity_type'], unique=False)
    op.create_index(op.f('idx_graph_entity_name_text'), 'graph_entity_attributes', [sa.literal_column("to_tsvector('english'::regconfig, name)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_graph_entity_group_id'), 'graph_entity_attributes', ['group_id'], unique=False)
    op.create_index(op.f('idx_graph_entity_embedding'), 'graph_entity_attributes', ['name_embedding'], unique=False, postgresql_ops={'name_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_graph_entity_attributes_jsonb'), 'graph_entity_attributes', ['attributes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
