/**
 * Rare event notification component.
 *
 * Displays spontaneous events/messages from the assistant
 * as floating toasts that can be dismissed.
 */

import { useEffect, useState } from "react";
import { X, Sparkles, MessageCircle, Eye, Brain, Sun } from "lucide-react";
import { api } from "@/lib/api";
import type { RareEvent, RareEventType } from "@/types/api";
import { useDashboardStore } from "@/stores/dashboard";
import { cn } from "@/lib/utils";

const EVENT_ICONS: Record<RareEventType, typeof Sparkles> = {
  note: MessageCircle,
  mood_shift: Sparkles,
  observation: Eye,
  memory: Brain,
  greeting: Sun,
};

const EVENT_LABELS: Record<RareEventType, string> = {
  note: "Note",
  mood_shift: "Mood",
  observation: "Noticed",
  memory: "Memory",
  greeting: "Hello",
};

interface RareEventToastProps {
  className?: string;
  pollInterval?: number;
}

export function RareEventToast({
  className,
  pollInterval = 30000,
}: RareEventToastProps) {
  const [event, setEvent] = useState<RareEvent | null>(null);
  const [visible, setVisible] = useState(false);
  const moodHue = useDashboardStore((s) => s.moodHue);

  useEffect(() => {
    const fetchPending = async () => {
      try {
        const pending = await api.rareEvents.pending();
        if (pending && !event) {
          setEvent(pending);
          setVisible(true);
          // Mark as shown
          await api.rareEvents.markShown(pending.id);
        }
      } catch {
        // Ignore fetch errors
      }
    };

    fetchPending();
    const interval = setInterval(fetchPending, pollInterval);
    return () => clearInterval(interval);
  }, [pollInterval, event]);

  const handleDismiss = async () => {
    if (event) {
      try {
        await api.rareEvents.dismiss(event.id);
      } catch {
        // Ignore
      }
    }
    setVisible(false);
    // Allow next event after animation
    setTimeout(() => setEvent(null), 300);
  };

  if (!event || !visible) {
    return null;
  }

  const Icon = EVENT_ICONS[event.event_type as RareEventType] || Sparkles;
  const label = EVENT_LABELS[event.event_type as RareEventType] || "Event";

  // Get display content from event
  const content = event.content as Record<string, unknown> | null;
  const displayText = getDisplayText(event.event_type as RareEventType, content);

  return (
    <div
      className={cn(
        "fixed bottom-20 right-4 z-50 max-w-sm",
        "animate-in slide-in-from-right fade-in duration-300",
        className
      )}
    >
      <div
        className="rounded-lg border bg-card p-4 shadow-lg"
        style={{
          borderColor: `hsl(${moodHue} 50% 40% / 0.5)`,
          boxShadow: `0 4px 20px hsl(${moodHue} 50% 30% / 0.15)`,
        }}
      >
        <div className="flex items-start gap-3">
          <div
            className="flex h-8 w-8 items-center justify-center rounded-full"
            style={{
              backgroundColor: `hsl(${moodHue} 50% 50% / 0.15)`,
              color: `hsl(${moodHue} 60% 50%)`,
            }}
          >
            <Icon className="h-4 w-4" />
          </div>

          <div className="flex-1 min-w-0">
            <div className="flex items-center justify-between mb-1">
              <span
                className="text-xs font-medium uppercase tracking-wide"
                style={{ color: `hsl(${moodHue} 40% 50%)` }}
              >
                {label}
              </span>
              <button
                onClick={handleDismiss}
                className="text-muted-foreground hover:text-foreground transition-colors"
                aria-label="Dismiss"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <p className="text-sm text-foreground/90">{displayText}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

function getDisplayText(
  eventType: RareEventType,
  content: Record<string, unknown> | null
): string {
  if (!content) {
    return "...";
  }

  // For now, return placeholder based on content hints
  // In production, this would be generated by LLM
  switch (eventType) {
    case "greeting": {
      const timeOfDay = content.time_of_day as string;
      const warmth = content.warmth as string;
      if (warmth === "high") {
        return timeOfDay === "morning"
          ? "Good morning! Ready to start the day?"
          : "Good evening! How was your day?";
      }
      return timeOfDay === "morning" ? "Morning." : "Evening.";
    }

    case "note": {
      const tone = content.tone as string;
      if (tone === "encouraging") {
        return "You're doing well today.";
      }
      return "Just checking in.";
    }

    case "observation": {
      const idleMinutes = content.idle_minutes as number;
      if (idleMinutes > 60) {
        return "It's been quiet for a while...";
      }
      if (idleMinutes > 30) {
        return "Taking a break?";
      }
      return "Still here.";
    }

    case "mood_shift": {
      const emotion = content.emotion as string;
      const intensity = content.intensity as number;
      if (intensity > 0.7) {
        return `Feeling ${emotion} right now.`;
      }
      return "Mood shift.";
    }

    case "memory": {
      const streakDays = content.streak_days as number;
      if (streakDays > 7) {
        return `${streakDays} days in a row. That means something.`;
      }
      return "Remembering something...";
    }

    default:
      return "...";
  }
}
