/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EmotionRouteImport } from './routes/emotion'
import { Route as AmbientRouteImport } from './routes/ambient'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionRoute = EmotionRouteImport.update({
  id: '/emotion',
  path: '/emotion',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientRoute = AmbientRouteImport.update({
  id: '/ambient',
  path: '/ambient',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambient': typeof AmbientRoute
  '/emotion': typeof EmotionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambient': typeof AmbientRoute
  '/emotion': typeof EmotionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambient': typeof AmbientRoute
  '/emotion': typeof EmotionRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambient'
    | '/emotion'
    | '/settings'
    | '/tasks'
    | '/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambient'
    | '/emotion'
    | '/settings'
    | '/tasks'
    | '/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/ambient'
    | '/emotion'
    | '/settings'
    | '/tasks'
    | '/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbientRoute: typeof AmbientRoute
  EmotionRoute: typeof EmotionRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotion': {
      id: '/emotion'
      path: '/emotion'
      fullPath: '/emotion'
      preLoaderRoute: typeof EmotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambient': {
      id: '/ambient'
      path: '/ambient'
      fullPath: '/ambient'
      preLoaderRoute: typeof AmbientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbientRoute: AmbientRoute,
  EmotionRoute: EmotionRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
