/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Activity tracking integration
 */
export type EnableActivityWatch = boolean;
/**
 * ActivityWatch server URL
 */
export type URL = string;
/**
 * Hours of activity to analyze
 */
export type ActivityLookback = number;
/**
 * How often to check for engagement
 */
export type CheckInterval = number;
/**
 * Threshold for context change detection
 */
export type ContextThreshold = number;
/**
 * Dere daemon API URL
 */
export type DaemonURL = string;
/**
 * Max embeddings to search
 */
export type EmbeddingLimit = number;
/**
 * Proactive notifications and check-ins
 */
export type EnableAmbient = boolean;
/**
 * Follow-up on ignored messages
 */
export type Escalation = boolean;
/**
 * Hours to check for unanswered messages
 */
export type EscalationLookback = number;
/**
 * Min/max minutes in cooldown state
 */
export type CooldownInterval = number[];
/**
 * State machine scheduling
 */
export type FSMMode = boolean;
/**
 * Minutes in engaged state
 */
export type EngagedInterval = number;
/**
 * Min/max minutes in escalating state
 */
export type EscalatingInterval = number[];
/**
 * Min/max minutes in idle state
 */
export type IdleInterval = number[];
/**
 * Min/max minutes in monitoring state
 */
export type MonitoringInterval = number[];
/**
 * Min/max minutes in suppressed state
 */
export type SuppressedInterval = number[];
/**
 * Weight for activity signal
 */
export type ActivityWeight = number;
/**
 * Weight for emotion signal
 */
export type EmotionWeight = number;
/**
 * Weight for responsiveness signal
 */
export type ResponsivenessWeight = number;
/**
 * Weight for task signal
 */
export type TaskWeight = number;
/**
 * Weight for temporal signal
 */
export type TemporalWeight = number;
/**
 * User idle time before engaging
 */
export type IdleThreshold = number;
/**
 * Minimum time between notifications
 */
export type MinNotifyInterval = number;
/**
 * How to send notifications
 */
export type NotificationMethod = string;
/**
 * Personality for ambient messages
 */
export type Personality = string | null;
/**
 * Delay before ambient starts
 */
export type StartupDelay = number;
/**
 * Override user ID
 */
export type UserID = string | null;
/**
 * Custom announcement messages
 */
export type Messages = string[];
/**
 * Include ActivityWatch data
 */
export type Activity = boolean;
/**
 * Use differential lookback between messages
 */
export type DifferentialMode = boolean;
/**
 * Gap threshold to trigger full lookback
 */
export type FullLookbackThreshold = number;
/**
 * Minutes of activity history
 */
export type ActivityLookback1 = number;
/**
 * Maximum activity duration to show
 */
export type MaxDuration = number;
/**
 * Minimum lookback for differential mode
 */
export type MinLookback = number;
/**
 * Include calendar events
 */
export type Calendar = boolean;
/**
 * Context output format
 */
export type Format = string;
/**
 * Use knowledge graph context
 */
export type KnowledgeGraph = boolean;
/**
 * Prefix XML context lines with numbers for precise editing
 */
export type LineNumbers = boolean;
/**
 * Truncate titles longer than this
 */
export type MaxTitleLength = number;
/**
 * Show currently playing media
 */
export type MediaPlayer = boolean;
/**
 * Show recently modified files
 */
export type RecentFiles = boolean;
/**
 * Root directory for recent files
 */
export type BasePath = string;
/**
 * Maximum directory depth
 */
export type MaxDepth = number;
/**
 * How far back to look for files
 */
export type RecentFilesTimeframe = string;
/**
 * Show duration for short activities
 */
export type ShowDuration = boolean;
/**
 * Show inactive context items
 */
export type ShowInactive = boolean;
/**
 * Include Taskwarrior tasks
 */
export type Tasks = boolean;
/**
 * Include current time
 */
export type Time = boolean;
/**
 * Auto-refresh interval (0 to disable)
 */
export type UpdateInterval = number;
/**
 * Include weather info
 */
export type Weather = boolean;
/**
 * Cache weather data for this long
 */
export type WeatherCache = number;
/**
 * PostgreSQL connection string
 */
export type DatabaseURL = string;
/**
 * Global default personality
 */
export type DefaultPersonality = string;
/**
 * Model for graph operations
 */
export type ClaudeModel = string;
/**
 * Vector embedding dimension
 */
export type EmbeddingDimension = number;
/**
 * Enable graph reflection processing
 */
export type EnableReflection = boolean;
/**
 * Knowledge graph integration
 */
export type EnableGraph = boolean;
/**
 * FalkorDB database name
 */
export type DatabaseName = string;
/**
 * FalkorDB server host
 */
export type FalkorDBHost = string;
/**
 * FalkorDB server port
 */
export type FalkorDBPort = number;
/**
 * Idle time before reflection
 */
export type IdleThreshold1 = number;
/**
 * Comma-separated channel IDs
 */
export type AllowedChannels = string;
/**
 * Comma-separated guild IDs
 */
export type AllowedGuilds = string;
/**
 * Include context in Discord messages
 */
export type ContextEnabled = boolean;
/**
 * Default personality for Discord
 */
export type DefaultPersona = string;
/**
 * Session timeout after inactivity
 */
export type IdleTimeout = number;
/**
 * Grace period before summarizing
 */
export type SummaryGrace = number;
/**
 * Discord bot token
 */
export type Token = string;
/**
 * Directories for auto mode
 */
export type Directories = string[];
/**
 * Plugin activation mode
 */
export type Mode = string;
/**
 * Your name shown in conversations
 */
export type DisplayName = string;
/**
 * System user identifier
 */
export type UserID1 = string;
/**
 * City name for weather lookup
 */
export type City = string | null;
/**
 * Fetch weather data for context
 */
export type EnableWeather = boolean;
/**
 * Temperature units
 */
export type Units = string;

/**
 * Main dere configuration with validation.
 */
export interface DereConfig {
  activitywatch?: ActivityWatch;
  ambient?: Ambient;
  announcements?: AnnouncementsConfig;
  context?: Context;
  database?: Database;
  default_personality?: DefaultPersonality;
  dere_graph?: KnowledgeGraph1;
  discord?: Discord;
  plugins?: Plugins;
  user?: User;
  user_id?: UserID1;
  weather?: Weather1;
  [k: string]: unknown;
}
/**
 * Activity tracking integration
 */
export interface ActivityWatch {
  enabled?: EnableActivityWatch;
  url?: URL;
  [k: string]: unknown;
}
/**
 * Proactive monitoring settings
 */
export interface Ambient {
  activity_lookback_hours?: ActivityLookback;
  check_interval_minutes?: CheckInterval;
  context_change_threshold?: ContextThreshold;
  daemon_url?: DaemonURL;
  embedding_search_limit?: EmbeddingLimit;
  enabled?: EnableAmbient;
  escalation_enabled?: Escalation;
  escalation_lookback_hours?: EscalationLookback;
  fsm_cooldown_interval?: CooldownInterval;
  fsm_enabled?: FSMMode;
  fsm_engaged_interval?: EngagedInterval;
  fsm_escalating_interval?: EscalatingInterval;
  fsm_idle_interval?: IdleInterval;
  fsm_monitoring_interval?: MonitoringInterval;
  fsm_suppressed_interval?: SuppressedInterval;
  fsm_weight_activity?: ActivityWeight;
  fsm_weight_emotion?: EmotionWeight;
  fsm_weight_responsiveness?: ResponsivenessWeight;
  fsm_weight_task?: TaskWeight;
  fsm_weight_temporal?: TemporalWeight;
  idle_threshold_minutes?: IdleThreshold;
  min_notification_interval_minutes?: MinNotifyInterval;
  notification_method?: NotificationMethod;
  personality?: Personality;
  startup_delay_seconds?: StartupDelay;
  user_id?: UserID;
  [k: string]: unknown;
}
/**
 * Personality announcement configuration.
 */
export interface AnnouncementsConfig {
  messages?: Messages;
  [k: string]: unknown;
}
/**
 * Context gathering settings
 */
export interface Context {
  activity?: Activity;
  activity_differential_enabled?: DifferentialMode;
  activity_full_lookback_threshold_minutes?: FullLookbackThreshold;
  activity_lookback_minutes?: ActivityLookback1;
  activity_max_duration_hours?: MaxDuration;
  activity_min_lookback_minutes?: MinLookback;
  calendar?: Calendar;
  format?: Format;
  knowledge_graph?: KnowledgeGraph;
  line_numbered_xml?: LineNumbers;
  max_title_length?: MaxTitleLength;
  media_player?: MediaPlayer;
  recent_files?: RecentFiles;
  recent_files_base_path?: BasePath;
  recent_files_max_depth?: MaxDepth;
  recent_files_timeframe?: RecentFilesTimeframe;
  show_duration_for_short?: ShowDuration;
  show_inactive_items?: ShowInactive;
  tasks?: Tasks;
  time?: Time;
  update_interval_seconds?: UpdateInterval;
  weather?: Weather;
  weather_cache_minutes?: WeatherCache;
  [k: string]: unknown;
}
/**
 * Database connection
 */
export interface Database {
  url?: DatabaseURL;
  [k: string]: unknown;
}
/**
 * Knowledge graph settings
 */
export interface KnowledgeGraph1 {
  claude_model?: ClaudeModel;
  embedding_dim?: EmbeddingDimension;
  enable_reflection?: EnableReflection;
  enabled?: EnableGraph;
  falkor_database?: DatabaseName;
  falkor_host?: FalkorDBHost;
  falkor_port?: FalkorDBPort;
  idle_threshold_minutes?: IdleThreshold1;
  [k: string]: unknown;
}
/**
 * Discord bot settings
 */
export interface Discord {
  allowed_channels?: AllowedChannels;
  allowed_guilds?: AllowedGuilds;
  context_enabled?: ContextEnabled;
  default_persona?: DefaultPersona;
  idle_timeout_seconds?: IdleTimeout;
  summary_grace_seconds?: SummaryGrace;
  token?: Token;
  [k: string]: unknown;
}
/**
 * Plugin activation modes
 */
export interface Plugins {
  dere_code?: DereCode;
  dere_core?: DereCore;
  dere_productivity?: DereProductivity;
  dere_vault?: DereVault;
  [k: string]: unknown;
}
/**
 * Code-related tools and context
 */
export interface DereCode {
  directories?: Directories;
  mode?: Mode;
  [k: string]: unknown;
}
/**
 * Core personality features
 */
export interface DereCore {
  directories?: Directories;
  mode?: Mode;
  [k: string]: unknown;
}
/**
 * Taskwarrior and calendar integration
 */
export interface DereProductivity {
  directories?: Directories;
  mode?: Mode;
  [k: string]: unknown;
}
/**
 * Zotero and document management
 */
export interface DereVault {
  directories?: Directories;
  mode?: Mode;
  [k: string]: unknown;
}
/**
 * User identity settings
 */
export interface User {
  name?: DisplayName;
  [k: string]: unknown;
}
/**
 * Weather data source
 */
export interface Weather1 {
  city?: City;
  enabled?: EnableWeather;
  units?: Units;
  [k: string]: unknown;
}
